from django.utils.translation import gettext as _

APIMODE_SANDBOX = 'sandbox'
APIMODE_LIVE = 'live'

APIMODE_CHOICES = [
    (APIMODE_SANDBOX, _('Sandbox')),
    (APIMODE_LIVE,    _('Live')),
]

# Products
PRODUCTS_ENDPOINT = '/v1/catalogs/products'

PRODUCT_TYPE_PHYSICAL = 'PHYSICAL'
PRODUCT_TYPE_DIGITAL  = 'DIGITAL'
PRODUCT_TYPE_SERVICE  = 'SERVICE'

PRODUCT_TYPES = [
    (PRODUCT_TYPE_PHYSICAL, _('Physical')),
    (PRODUCT_TYPE_DIGITAL,  _('Digital')),
    (PRODUCT_TYPE_SERVICE,  _('Service')),
]

# Plans
PLANS_ENDPOINT = '/v1/billing/plans'

PLAN_STATUS_CREATED  = _('CREATED')
PLAN_STATUS_INACTIVE = _('INACTIVE')
PLAN_STATUS_ACTIVE   = _('ACTIVE')

PLAN_STATUS_CHOICES = [
    (PLAN_STATUS_CREATED,  _('Created')),
    (PLAN_STATUS_INACTIVE, _('Inactive')),
    (PLAN_STATUS_ACTIVE,   _('Active')),
]

# Subscriptions
SUBSCRIPTIONS_ENDPOINT = '/v1/billing/subscriptions'

SUBSCRIPTION_STATUS_APPROVAL_PENDING = 'APPROVAL_PENDING'
SUBSCRIPTION_STATUS_APPROVED         = 'APPROVED'
SUBSCRIPTION_STATUS_ACTIVE           = 'ACTIVE'
SUBSCRIPTION_STATUS_SUSPENDED        = 'SUSPENDED'
SUBSCRIPTION_STATUS_CANCELLED        = 'CANCELLED'
SUBSCRIPTION_STATUS_EXPIRED          = 'EXPIRED'

SUBSCRIPTION_STATUS_CHOICES = [
    (SUBSCRIPTION_STATUS_APPROVAL_PENDING, _('Approval pending')),
    (SUBSCRIPTION_STATUS_APPROVED,         _('Approved')),
    (SUBSCRIPTION_STATUS_ACTIVE,           _('Active')),
    (SUBSCRIPTION_STATUS_SUSPENDED,        _('Suspended')),
    (SUBSCRIPTION_STATUS_CANCELLED,        _('Cancelled')),
    (SUBSCRIPTION_STATUS_EXPIRED,          _('Expired')),
]

ORDER_INTENT_CAPTURE   = 'CAPTURE'
ORDER_INTENT_AUTHORIZE = 'AUTHORIZE'

ORDER_INTENT_CHOICES = (
    (ORDER_INTENT_CAPTURE,   _('Capture')),
    (ORDER_INTENT_AUTHORIZE, _('Authorize')),
)

ORDER_STATUS_CREATED   = 'CREATED'
ORDER_STATUS_SAVED     = 'SAVED'
ORDER_STATUS_APPROVED  = 'APPROVED'
ORDER_STATUS_VOIDED    = 'VOIDED'
ORDER_STATUS_COMPLETED = 'COMPLETED'

ORDER_STATUS_CHOICES = (
    (ORDER_STATUS_CREATED,   _('Created')),
    (ORDER_STATUS_SAVED,     _('Saved')),
    (ORDER_STATUS_APPROVED,  _('Approved')),
    (ORDER_STATUS_VOIDED,    _('Voided')),
    (ORDER_STATUS_COMPLETED, _('Completed')),
)

CAPTURE_STATUS_COMPLETED          = 'COMPLETED'
CAPTURE_STATUS_DECLINED           = 'DECLINED'
CAPTURE_STATUS_PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED'
CAPTURE_STATUS_PENDING            = 'PENDING'
CAPTURE_STATUS_REFUNDED           = 'REFUNDED'

CAPTURE_STATUS_CHOICES = (
    (CAPTURE_STATUS_COMPLETED,          _('Completed')),
    (CAPTURE_STATUS_DECLINED,           _('Declined')),
    (CAPTURE_STATUS_PARTIALLY_REFUNDED, _('Partially refunded')),
    (CAPTURE_STATUS_PENDING,            _('Pending')),
    (CAPTURE_STATUS_REFUNDED,           _('Refunded')),
)

DISBURSEMENT_MODE_INSTANT = 'INSTANT'
DISBURSEMENT_MODE_DELAYED = 'DELAYED'

DISBURSEMENT_MODE_CHOICES = (
    (DISBURSEMENT_MODE_INSTANT, _('Instant')),
    (DISBURSEMENT_MODE_DELAYED, _('Delayed')),
)
