# Generated by Django 2.2.9 on 2020-08-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djpp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='payer_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djpp.Payer'),
        ),
    ]
